---
- hosts: all
  sudo: yes
  remote_user: root

  vars:
    main_nodejss_ipc: "{% set IP_ARR=[] %}{% for host in groups['all'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_default_ipv4']['address']) %}{% endif %}{% endfor %}{{IP_ARR|join(',')}}"
    ipv4_master_addr: "{{ hostvars[groups['all'][0]]['ansible_default_ipv4']['address'] }}"

  vars_files:
    - "{{ var_file }}"

  tasks:

  - name: update apt
    apt: update_cache=yes

  - name: update puppet 
    command: "prun safe"

  - name: ensure packages installed
    apt: pkg={{ item }} state=latest
    with_items:
      - "nodejs"

