---
- hosts: all
  remote_user: root

  vars:
    main_nodes_ips: "{% set IP_ARR=[] %}{% for host in groups['all'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_default_ipv4']['address']) %}{% endif %}{% endfor %}{{IP_ARR|join(' ')}}"
    main_nodes_ipc: "{% set IP_ARR=[] %}{% for host in groups['all'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_default_ipv4']['address']) %}{% endif %}{% endfor %}{{IP_ARR|join(',')}}"
    ipv4_master_addr: "{{ hostvars[groups['all'][0]]['ansible_default_ipv4']['address'] }}"

  vars_files:
    - "{{ var_file }}"

  tasks:

  - name: update apt
    apt: update_cache=yes

  - name: ensure proftpd is installed
    apt: pkg=proftpd state=latest

  - name: deploy proftpd.conf
    copy:
      src: files/proftpd/proftpd.conf
      dest: /etc/proftpd/proftpd.conf
      owner: root
      group: root
      mode: 0644

  - name: create identity files
    file:
      path: /etc/proftpd/{{ item }}
      state: touch
      owner: root
      group: root
      mode: 0600
    with_items:
      - ftpd.passwd
      - ftpd.group

  - name: create authorized keys directory
    file:
      path: /etc/proftpd/authorized_keys.d
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: restart proftpd
    service:
      name: proftpd
      state: restarted
