---
- include: tasks/debian.yml
  when: ansible_os_family == "Debian"

- name: checking to see if already clustered
  stat: path=/etc/mysql/clustered
  register: clustered

- include: tasks/mysql_clustering.yml
  when: enable_mysql_clustering and (clustered.stat.exists != True)

- include: tasks/mysql_ha_config.yml
  when: config_mysql_ha and enable_mysql_clustering
