---

- name: "template keepalived.conf for master"
  when: ip.master in ansible_all_ipv4_addresses
  blockinfile:
    dest: /etc/keepalived/keepalived.conf
    block: "{{ lookup('template', 'keepalived_master.conf') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ ip.name }}"

- name: "template keepalived.conf for slave"
  when: ip.slave in ansible_all_ipv4_addresses
  blockinfile:
    dest: /etc/keepalived/keepalived.conf
    block: "{{ lookup('template', 'keepalived_slave.conf') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ ip.name }}"

